"""
Quick Setup Script
Helps users configure the automation system
"""

import os
import sys
import json
from pathlib import Path


def print_banner():
    """Print welcome banner"""
    print("""
╔══════════════════════════════════════════════════════════╗
║   YouTube & TikTok Auto-Posting System - Setup Wizard   ║
╚══════════════════════════════════════════════════════════╝
""")


def check_python_version():
    """Check Python version"""
    version = sys.version_info
    if version.major < 3 or (version.major == 3 and version.minor < 9):
        print(f"❌ Python 3.9+ required. You have {version.major}.{version.minor}")
        sys.exit(1)
    print(f"✓ Python {version.major}.{version.minor} detected")


def check_ffmpeg():
    """Check if FFmpeg is installed"""
    result = os.system("ffmpeg -version > nul 2>&1")
    if result == 0:
        print("✓ FFmpeg is installed")
        return True
    else:
        print("⚠️  FFmpeg not found. Videos won't be created properly.")
        print("   Install from: https://ffmpeg.org/download.html")
        return False


def setup_env_file():
    """Setup .env file with user input"""
    
    if os.path.exists(".env"):
        response = input("\n.env file already exists. Overwrite? (y/n): ").lower()
        if response != 'y':
            print("✓ Keeping existing .env file")
            return
    
    print("\n" + "="*60)
    print("🔑 API CONFIGURATION")
    print("="*60)
    
    env_vars = {}
    
    # OpenAI
    print("\n1️⃣  OpenAI API Setup")
    print("   Get from: https://platform.openai.com/api-keys")
    openai_key = input("Enter OpenAI API Key (or press Enter to skip): ").strip()
    if openai_key:
        env_vars['OPENAI_API_KEY'] = openai_key
    
    # YouTube
    print("\n2️⃣  YouTube API Setup")
    print("   Get from: https://console.cloud.google.com/")
    print("   Need: Client ID, Client Secret, Refresh Token")
    
    yt_client_id = input("Enter YouTube Client ID (or press Enter to skip): ").strip()
    if yt_client_id:
        env_vars['YOUTUBE_CLIENT_ID'] = yt_client_id
    
    yt_client_secret = input("Enter YouTube Client Secret: ").strip()
    if yt_client_secret:
        env_vars['YOUTUBE_CLIENT_SECRET'] = yt_client_secret
    
    yt_refresh_token = input("Enter YouTube Refresh Token: ").strip()
    if yt_refresh_token:
        env_vars['YOUTUBE_REFRESH_TOKEN'] = yt_refresh_token
    
    # TikTok
    print("\n3️⃣  TikTok API Setup")
    print("   Get from: https://developer.tiktok.com/")
    
    tiktok_access = input("Enter TikTok Access Token (or press Enter to skip): ").strip()
    if tiktok_access:
        env_vars['TIKTOK_ACCESS_TOKEN'] = tiktok_access
    
    tiktok_refresh = input("Enter TikTok Refresh Token: ").strip()
    if tiktok_refresh:
        env_vars['TIKTOK_REFRESH_TOKEN'] = tiktok_refresh
    
    # Posting time
    print("\n4️⃣  Posting Configuration")
    posting_time = input("Enter daily posting time (HH:MM, e.g., 09:00): ").strip()
    if posting_time:
        env_vars['POSTING_TIME'] = posting_time
    else:
        env_vars['POSTING_TIME'] = '09:00'
    
    # Write .env file
    try:
        with open(".env", "w") as f:
            f.write("# YouTube & TikTok Auto-Posting System Configuration\n")
            f.write("# Generated by setup script\n\n")
            
            for key, value in env_vars.items():
                f.write(f"{key}={value}\n")
        
        print("\n✓ .env file created successfully!")
    except Exception as e:
        print(f"❌ Error creating .env file: {e}")


def check_dependencies():
    """Check if required Python packages are installed"""
    
    try:
        import openai
        print("✓ openai package installed")
    except ImportError:
        print("⚠️  openai package not found")
    
    try:
        import google.auth
        print("✓ google-auth package installed")
    except ImportError:
        print("⚠️  google-auth package not found")
    
    try:
        import moviepy
        print("✓ moviepy package installed")
    except ImportError:
        print("⚠️  moviepy package not found")
    
    try:
        import apscheduler
        print("✓ apscheduler package installed")
    except ImportError:
        print("⚠️  apscheduler package not found")


def install_dependencies():
    """Install required packages"""
    response = input("\nInstall/update all dependencies? (y/n): ").lower()
    if response == 'y':
        print("⏳ Installing packages...")
        os.system("pip install -r requirements.txt")
        print("✓ Dependencies installed")


def test_openai():
    """Test OpenAI connection"""
    try:
        import openai
        from dotenv import load_dotenv
        
        load_dotenv()
        api_key = os.getenv('OPENAI_API_KEY')
        
        if not api_key:
            print("⚠️  OpenAI API key not found in .env")
            return False
        
        openai.api_key = api_key
        
        print("⏳ Testing OpenAI connection...")
        response = openai.ChatCompletion.create(
            model="gpt-4",
            messages=[{"role": "user", "content": "Say 'Hello'"}],
            max_tokens=10
        )
        
        if response:
            print("✓ OpenAI API connection successful!")
            return True
    
    except Exception as e:
        print(f"❌ OpenAI connection failed: {e}")
        return False


def create_folders():
    """Create necessary directories"""
    folders = [
        "logs",
        "generated_content",
        "thumbnails",
        "videos"
    ]
    
    for folder in folders:
        os.makedirs(folder, exist_ok=True)
    
    print(f"✓ Created {len(folders)} directories")


def show_next_steps():
    """Show next steps for user"""
    print("\n" + "="*60)
    print("✅ SETUP COMPLETE!")
    print("="*60)
    
    print("\n📋 Next Steps:")
    print("\n1. Test the system:")
    print("   python main.py once")
    print("\n2. Check if posts appear on YouTube and TikTok")
    print("\n3. Start the daily scheduler:")
    print("   python main.py start")
    print("\n4. Monitor logs:")
    print("   tail -f logs/automation.log")
    print("\n5. For deployment to cloud:")
    print("   Read the 'Deploying to Cloud Server' section in README.md")
    
    print("\n📚 Documentation: README.md")
    print("🔧 Configuration: .env")
    print("📊 Logs: logs/automation.log")


def main():
    """Main setup flow"""
    
    print_banner()
    
    # Checks
    print("\n" + "="*60)
    print("🔍 SYSTEM CHECKS")
    print("="*60)
    
    check_python_version()
    check_ffmpeg()
    
    # Create directories
    print("\n📁 Creating directories...")
    create_folders()
    
    # Check dependencies
    print("\n" + "="*60)
    print("📦 DEPENDENCY CHECK")
    print("="*60)
    check_dependencies()
    install_dependencies()
    
    # Setup environment
    setup_env_file()
    
    # Test OpenAI
    print("\n" + "="*60)
    print("🧪 TESTING CONNECTIONS")
    print("="*60)
    test_openai()
    
    # Show next steps
    show_next_steps()
    
    print("\n")


if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        print("\n\n❌ Setup cancelled by user")
        sys.exit(1)
